### PR TITLE
RFC: add initial minimal viable product RFC

### LINKED ISSUE #4: Decide on the set of features to include in the Initial Minimal Viable Product
Previous ideas included, but not limit to:

- UCL restaurants and cafe guide
- UCL libraries + study spaces
  - Occupancy rate / availability / opening/closing date-times
- UCL map
  - Tour
- Travel to and from UCL campus
  - London Underground
  - Buses
- Advices for newcomers
  - Accommodation
- UCL module selection/catalogue "remake"?
  - We improve the existing catalogue by making it easier to view and read
- UCL reading list improvement?
- Student Forum
  - Study advices – effective study strategies?
  - Subject resources and exam review materials
    - Temporarily disabled during live examination period (30-day warning)
    - We cannot be liable of copyright infringement, so the uploader must either:
      - Prove that they got written consent from the copyright holder; or
      - The material is free in terms of creative commons; or
      - The material is notes for multiple sources but contains proper in-text citations and a bibliography.
  - Subject course content discussion
    - For on-going lectures
  - Second-hand market (we only facilitate "a place of initiation") – items, rent
    - We don't handle money; the buyer/seller themselves are responsible for the actual trade.
    - We need to display scam/personal safety warning (e.g. ONLY trade on-campus?)
  - Module selection advices
  - New-comer advice
    - Aka personal tutor content
  - Programming tutor content
- Where to get help?
  - Personal tutor / departmental tutor
  - Registration status changes
  - Module changes
  - Program changes
  - Career advice – refer to the careers team
- Immigration advice – taken from UK official website (disclaimer: NOT official)
  - Tier 4 visa info
  - Police registration – for international students
- Restaurants and takeaways
- Coronavirus information
  - Daily updates: case counts, distribution, location, trends
  - Protection
  - Vaccine development status – use information from WHO
  - Link to important COVID-19 papers for those interested

We should **deduplicate**, **categorize** and **prioritize** these feature ideas. Design team members please edit the list to add additional ideas or to modify existing ideas.

### PR DESCRIPTION
**Pull request by jieyouxu**
This PR adds the RFC for the Initial Minimal Viable Product, as discussed in the Design Team meeting minutes (available at: https://github.com/UCLHub/meeting-minutes/blob/master/design/2020-09-24.md).

Please carefully review the proposed RFC @UCLHub/design team members.

Closes #4.

### CODE REVIEW

**Comment by jieyouxu** [comment]
Because this is a foundational RFC, I propose that this RFC be immediately accepted if we have 2/3 of the votes of the members of the design team (fast-fowarded).

### Required Votes

Once we have 2/3 of the votes for the decision to accept this RFC, this RFC will be accepted and assigned an RFC document number (please make sure to edit the RFC document number) and the PR will be merged.

The following design team members (@UCLHub/design) need to agree to the FCP decision:

- [x] @jieyouxu
- [x]  @henryz00
- [x] @DaviesXue 

Please edit this comment to vote to **accept** this RFC *immediately*.

**Comment by Davi-X** [comment]
@jieyouxu **Nice!**

**Review by Davi-X — DISMISSED** [review]

**Review by henryzt — DISMISSED** [review]

**Comment by henryzt** [comment]
LGGGGTM🎉

**Comment by jieyouxu** [comment]
Now that we have 2/3 of the votes from members of the @UCLHub/design team, I declare this RFC to be **accepted**. 🎉

This RFC is issued the **RFC document number**: `RFC 0002`.

Please edit the RFC document to reflect this assigned document number.

**Review by henryzt — APPROVED** [review]

**Pull request merged**
