### PR TITLE
RFC: Add template Request for Comments

### PR DESCRIPTION
**Pull request by jieyouxu**
:warning: **Warning** :warning:: this PR creates the new folder, `rfcs/`, for which new RFCs shall be placed into!

Please help me review this RFC template as it will be *very* commonly used.

### PR History

- Reformatted to limit to `80` columns, aligned table.

### CODE REVIEW

**Review by henryzt — APPROVED** [review]
Great work! LGTM 👍

**Comment by jieyouxu** [comment]
As a development team member, I propose to start the **Final Comment Period** (FCP) to **accept** this RFC.

### Required Votes

Once we have 2/3 of the votes *for* the FCP decision to **accept** this RFC before **2020-09-29**, this RFC will be **accepted** and assigned an **RFC document number** (please make sure to edit the RFC document number) and the PR will be merged. If this FCP decision does not have sufficient votes before the deadline, this FCP process will be *aborted* and a team member will have to reinitiate the FCP process.

The following team members need to agree to the FCP decision:

- [x] @jieyouxu
- [x] @henryz00

Please edit this comment to vote for the FCP.

**Comment by jieyouxu** [comment]
As one of the series of foundational RFCs, I propose that we fast-foward this FCP process to **immediately accept** this RFC.

As a development team member, I agree to merge this RFC:

- [x] @jieyouxu 
- [x] @henryz00

**Comment by jieyouxu** [comment]
Now that we have 2/3 of the votes from members of the development team, I declare this RFC to be **accepted**. :tada:

This RFC is issued the **RFC document number**: `RFC 0000`.

Please edit the RFC document to reflect this assigned document number.

**Pull request merged**
